//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tililaskuri.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tililaskuri.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonEdistymisPalkki.
        /// </summary>
        public static string ButtonEdistymisPalkki {
            get {
                return ResourceManager.GetString("ButtonEdistymisPalkki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonHae.
        /// </summary>
        public static string ButtonHae {
            get {
                return ResourceManager.GetString("ButtonHae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBoxEdistymispalkki.
        /// </summary>
        public static string CheckBoxEdistymispalkki {
            get {
                return ResourceManager.GetString("CheckBoxEdistymispalkki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBoxHaeEhdolla.
        /// </summary>
        public static string CheckBoxHaeEhdolla {
            get {
                return ResourceManager.GetString("CheckBoxHaeEhdolla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemKohde.
        /// </summary>
        public static string ComboBoxItemKohde {
            get {
                return ResourceManager.GetString("ComboBoxItemKohde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemPvm.
        /// </summary>
        public static string ComboBoxItemPvm {
            get {
                return ResourceManager.GetString("ComboBoxItemPvm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemSelitys.
        /// </summary>
        public static string ComboBoxItemSelitys {
            get {
                return ResourceManager.GetString("ComboBoxItemSelitys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemSumma.
        /// </summary>
        public static string ComboBoxItemSumma {
            get {
                return ResourceManager.GetString("ComboBoxItemSumma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemTilinumero.
        /// </summary>
        public static string ComboBoxItemTilinumero {
            get {
                return ResourceManager.GetString("ComboBoxItemTilinumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGridHeaderKohde.
        /// </summary>
        public static string DataGridHeaderKohde {
            get {
                return ResourceManager.GetString("DataGridHeaderKohde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGridHeaderPvm.
        /// </summary>
        public static string DataGridHeaderPvm {
            get {
                return ResourceManager.GetString("DataGridHeaderPvm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGridHeaderSelitys.
        /// </summary>
        public static string DataGridHeaderSelitys {
            get {
                return ResourceManager.GetString("DataGridHeaderSelitys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGridHeaderSumma.
        /// </summary>
        public static string DataGridHeaderSumma {
            get {
                return ResourceManager.GetString("DataGridHeaderSumma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGridHeaderTilinumero.
        /// </summary>
        public static string DataGridHeaderTilinumero {
            get {
                return ResourceManager.GetString("DataGridHeaderTilinumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGridMenuLisääMaksu.
        /// </summary>
        public static string DataGridMenuLisääMaksu {
            get {
                return ResourceManager.GetString("DataGridMenuLisääMaksu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGridMenuLisääMaksuja.
        /// </summary>
        public static string DataGridMenuLisääMaksuja {
            get {
                return ResourceManager.GetString("DataGridMenuLisääMaksuja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGridMenuPoistaMaksuja.
        /// </summary>
        public static string DataGridMenuPoistaMaksuja {
            get {
                return ResourceManager.GetString("DataGridMenuPoistaMaksuja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelEdistymisPalkki.
        /// </summary>
        public static string LabelEdistymisPalkki {
            get {
                return ResourceManager.GetString("LabelEdistymisPalkki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelMenot.
        /// </summary>
        public static string LabelMenot {
            get {
                return ResourceManager.GetString("LabelMenot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelTulot.
        /// </summary>
        public static string LabelTulot {
            get {
                return ResourceManager.GetString("LabelTulot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelYhteensa.
        /// </summary>
        public static string LabelYhteensa {
            get {
                return ResourceManager.GetString("LabelYhteensa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuApua.
        /// </summary>
        public static string MenuApua {
            get {
                return ResourceManager.GetString("MenuApua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemAvaa.
        /// </summary>
        public static string MenuItemAvaa {
            get {
                return ResourceManager.GetString("MenuItemAvaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemKieli.
        /// </summary>
        public static string MenuItemKieli {
            get {
                return ResourceManager.GetString("MenuItemKieli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemOhje.
        /// </summary>
        public static string MenuItemOhje {
            get {
                return ResourceManager.GetString("MenuItemOhje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemSulje.
        /// </summary>
        public static string MenuItemSulje {
            get {
                return ResourceManager.GetString("MenuItemSulje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemTallenna.
        /// </summary>
        public static string MenuItemTallenna {
            get {
                return ResourceManager.GetString("MenuItemTallenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemTulosta.
        /// </summary>
        public static string MenuItemTulosta {
            get {
                return ResourceManager.GetString("MenuItemTulosta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuLisääMaksu.
        /// </summary>
        public static string MenuLisääMaksu {
            get {
                return ResourceManager.GetString("MenuLisääMaksu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuLisääMaksuja.
        /// </summary>
        public static string MenuLisääMaksuja {
            get {
                return ResourceManager.GetString("MenuLisääMaksuja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuMuokkaa.
        /// </summary>
        public static string MenuMuokkaa {
            get {
                return ResourceManager.GetString("MenuMuokkaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuPoistaMaksuja.
        /// </summary>
        public static string MenuPoistaMaksuja {
            get {
                return ResourceManager.GetString("MenuPoistaMaksuja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuTiedosto.
        /// </summary>
        public static string MenuTiedosto {
            get {
                return ResourceManager.GetString("MenuTiedosto", resourceCulture);
            }
        }
    }
}
