//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UusiMaksu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UusiMaksu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonOK.
        /// </summary>
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonPeruuta.
        /// </summary>
        internal static string ButtonPeruuta {
            get {
                return ResourceManager.GetString("ButtonPeruuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelKohde.
        /// </summary>
        internal static string LabelKohde {
            get {
                return ResourceManager.GetString("LabelKohde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelPvm.
        /// </summary>
        internal static string LabelPvm {
            get {
                return ResourceManager.GetString("LabelPvm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelSelitys.
        /// </summary>
        internal static string LabelSelitys {
            get {
                return ResourceManager.GetString("LabelSelitys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelSumma.
        /// </summary>
        internal static string LabelSumma {
            get {
                return ResourceManager.GetString("LabelSumma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelTiedot.
        /// </summary>
        internal static string LabelTiedot {
            get {
                return ResourceManager.GetString("LabelTiedot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelTilinumero.
        /// </summary>
        internal static string LabelTilinumero {
            get {
                return ResourceManager.GetString("LabelTilinumero", resourceCulture);
            }
        }
    }
}
